# -*- mode: org; fill-column: 79; -*-

#+TITLE: \bfseries Child Protection
#+SUBTITLE: Children's Rights in Theory and Practice\\
#+SUBTITLE: \slshape -- Harvard University --\\
#+SUBTITLE: \hrulefill
#+AUTHOR: \textsf{Outline by W. Lincoln Harvey}
#+CREATOR: Harvard University
#+DATE: 2019-01-16 Wed 14:08 ({{{VERSION}}} -- {{{EDITION}}})
#+MACRO: VERSION Version 0.0.1
#+MACRO: EDITION Edition 0.1

#+BEGIN_abstract
Learn how to protect children from violence, exploitation, and neglect
through law, policy, and practice in a human rights framework.

Across the world, children are at risk from violence, abuse,
exploitation, and neglect. Conflict and natural disasters have forced
millions to flee their homes and confront the dangers of migration and
displacement. Commercial sexual exploitation and trafficking, child
labor, and child marriage are problems in many countries. At-risk
children and adolescents need their rights enforced if we are to
protect them from harm and to ensure that they develop to their full
potential.

\index{Bhabha, Jacqueline}
Led by Jacqueline Bhabha, Research Director of the Harvard FXB Center
for Health and Human Rights, this course will teach you the causes and
consequences of child protection failures. You will consider the
strategies, international laws, standards, and resources required to
protect all children. You will be able to link legal frameworks and
child-rights approaches to the work of policymakers, lawyers, health
workers, educators, law enforcement, and social workers. Learners will
come to understand how they can ensure the protection of children and
apply child protection strategies to their own work.

Join Harvard faculty, practitioners, and a global community of
learners to master a child-centered systems approach to preventing and
responding to violence, exploitation, and abuse against children.
#+END_abstract

* Introduction
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

  {{{author}}} of the course ``@@latex:{\sc@@ Child
  Protection@@latex:}@@: @@latex:\emph{@@Children's Rights in Theory
  and Practice@@latex:}@@'' ({{{VERSION}}} {{{EDITION}}}) presented by
  Harvard University on edX, found at: [[https://online-learning.harvard.edu/course/child-protection-childrens-rights-theory-and-practice][Child Protection on
  HarvardX]]. \vspace{1cm}

  \textbf{Some topics covered are:}

   - The origins of child protection in international human rights law
   - How to analyze global child protection issues and the diversity
     of actors involved in child protection
   - The impact of violence, exploitation, and abuse (VEA) on
     children’s emotional, social and physical development and
     strategies for preventing and responding to these harms
   - The standards of protection for children in conflict or in
     contact with the law
   - How to assess and strengthen a child protection system

* Every Child's Right to Protection

  The Legal Foundation of Child Protection

  Defining and Measuring Child Protection

* Violence Against Children

* Children and the Law

* A System's Approach to Child Protection

* Index
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  \printindex


* EXPORT SETTINGS                                                  :noexport:
#+LATEX_CLASS: report
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage{makeidx}
#+LATEX_HEADER_EXTRA: \hypersetup{colorlinks=true}
#+LATEX_HEADER_EXTRA: \makeindex
#+DESCRIPTION:
#+KEYWORDS:
#+LATEX_COMPILER: xelatex
